Repository NVIDIA/cccl, pull requests merged in 2023-11, with the labels that each got.

#651 Fix C++11 support of recently added tests
  libcudacxx/.upstream-tests/test/cuda/barrier/cp_async_bulk_tensor_1d.pass.cpp
  libcudacxx/.upstream-tests/test/cuda/barrier/cp_async_bulk_tensor_2d.pass.cpp
  libcudacxx/.upstream-tests/test/cuda/barrier/cp_async_bulk_tensor_3d.pass.cpp
  libcudacxx/.upstream-tests/test/cuda/barrier/cp_async_bulk_tensor_4d.pass.cpp
  libcudacxx/.upstream-tests/test/cuda/barrier/cp_async_bulk_tensor_5d.pass.cpp
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/barrier.h
Labels: backport branch/2.3.x

#574 Add `cuda::ptx::*` namespace
  libcudacxx/.upstream-tests/test/cuda/ptx/ptx.mbarrier.arrive.compile.pass.cpp
  libcudacxx/.upstream-tests/test/support/concurrent_agents.h
  libcudacxx/docs/extended_api.md
  libcudacxx/docs/extended_api/ptx.md
  libcudacxx/include/cuda/ptx
  libcudacxx/include/cuda/std/detail/libcxx/include/__config
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/barrier.h
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx.h
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx/parallel_synchronization_and_communication_instructions_mbarrier.h
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx/ptx_dot_variants.h
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx/ptx_helper_functions.h
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx/ptx_isa_target_macros.h
Labels: backport branch/2.3.x

#652 Add CCCL_VERSION and script for updating version
  README.md
  ci/update_version.sh
  cub/cub/cmake/cub-config-version.cmake
  cub/cub/version.cuh
  lib/cmake/cccl/cccl-config-version.cmake
  libcudacxx/.upstream-tests/test/cuda/version.pass.cpp
  libcudacxx/include/cuda/std/detail/__config
  libcudacxx/include/cuda/std/detail/libcxx/include/__cccl/version.h
  libcudacxx/include/cuda/version
  libcudacxx/lib/cmake/libcudacxx/libcudacxx-config-version.cmake
  thrust/thrust/cmake/thrust-config-version.cmake
  thrust/thrust/version.h
Labels: backport branch/2.3.x

#666 Fixes compiler error for extended fp type data gen
  cub/test/bfloat16.h
  cub/test/c2h/generators.cu
  cub/test/half.h
Labels: cub

#664 fixup `___CUDA_VPTX` -> `_CUDA_VPTX`
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/barrier.h
Labels: backport branch/2.3.x

#625 Project automation - fix sync action and draft setting step
  .github/workflows/project_automation_set_in_progress.yml
  .github/workflows/project_automation_sync_pr_issues.yml
  .github/workflows/triage_rotation.yml
Labels: bug, infrastructure

#1085 Fix fallback when checking git repo
  ci/build_common.sh
Labels: backport branch/2.3.x

#1088 Currently the verbose option does not work beacuse of a typo in the argument handling
  ci/build_common.sh
Labels: backport branch/2.3.x

#1078 Add `cuda::ptx::st_async`
  libcudacxx/.upstream-tests/test/cuda/ptx/ptx.st.async.compile.pass.cpp
  libcudacxx/docs/extended_api/ptx.md
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx.h
Labels: backport branch/2.3.x

#1080 Add `cuda::ptx::red_async`
  libcudacxx/.upstream-tests/test/cuda/ptx/ptx.red.async.compile.pass.cpp
  libcudacxx/docs/extended_api/ptx.md
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx.h
Labels: backport branch/2.3.x

#674 Add `cuda::ptx:mbarrier_{try/test}_wait{_parity}`
  libcudacxx/docs/extended_api/ptx.md
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx/parallel_synchronization_and_communication_instructions_mbarrier.h
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.mbarrier.wait.compile.pass.cpp
Labels: backport branch/2.3.x

#1102 Fix `cuda::ptx::red.async` for int32_t types
  libcudacxx/docs/extended_api/ptx.md
  libcudacxx/include/cuda/std/detail/libcxx/include/__cuda/ptx.h
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.red.async.compile.pass.cpp
Labels: backport branch/2.3.x

#1108 Fix local test runs with lit
  libcudacxx/test/libcudacxx/lit.site.cfg.in
  libcudacxx/test/utils/libcudacxx/test/config.py
Labels: backport branch/2.3.x

#1115 Do not replace the sccache binary for windows
  ci/windows/build_common.psm1
Labels: infrastructure

#1130 Fix GCC6 / FP8 warning
  cub/cub/util_type.cuh
Labels: backport branch/2.3.x

#1132 Fix `ptx.st.async.compile.pass.cpp` failing in C++11.
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.st.async.compile.pass.cpp
Labels: backport branch/2.3.x

#1114 Fix `_LIBCUDACXX_UNREACHABLE` for old MSVC
  libcudacxx/include/cuda/std/detail/libcxx/include/array
  libcudacxx/include/cuda/std/detail/libcxx/include/cstdlib
Labels: nvbug, libcu++, backport branch/2.3.x, bug: functional

#1145 Fix argument name in windows CI
  .github/workflows/dispatch-build-and-test.yml
  ci/windows/build_common.psm1
  ci/windows/build_cub.ps1
  ci/windows/build_libcudacxx.ps1
  ci/windows/build_thrust.ps1
Labels: infrastructure

#1144 Fix XFAIL condition for subsumption tests
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/alg.req.ind.copy/indirectly_copyable.subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/alg.req.ind.move/indirectly_movable.subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/iterator.concepts/iterator.concept.bidir/subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/iterator.concepts/iterator.concept.forward/subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/iterator.concepts/iterator.concept.inc/subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/iterator.concepts/iterator.concept.input/subsumption.compile.pass.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.requirements/iterator.concepts/iterator.concept.iterator/subsumption.compile.pass.cpp
Labels: nvbug, libcu++, bug, backport branch/2.3.x

#1157 Fix errors when find_package(CCCL) is called twice.
  lib/cmake/cccl/cccl-config.cmake
  test/cmake/test_export/CMakeLists.txt
Labels: thrust, bug, infrastructure, backport branch/2.3.x

#1152 Fix icc / cub
  cub/cub/util_macro.cuh
  libcudacxx/include/cuda/std/detail/libcxx/include/__cccl_config
Labels: backport branch/2.3.x

#1143 BACKPORT: Fix `_LIBCUDACXX_UNREACHABLE` for old MSVC (#1114)
  libcudacxx/include/cuda/std/detail/libcxx/include/cstdlib
Labels: nvbug, libcu++
