Repository NVIDIA/cccl, pull requests merged in 2025-04, with the labels that each got.

#4275 [STF] dispatch content of stf.cuh into internal headers
  cudax/include/cuda/experimental/__stf/internal/algorithm.cuh
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/data_interface.cuh
  cudax/include/cuda/experimental/__stf/internal/for_each_batched.cuh
  cudax/include/cuda/experimental/__stf/utility/nvtx.cuh
  cudax/include/cuda/experimental/stf.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/examples/07-cholesky-unified.cu
Labels: stf

#4313 [STF] Add task_count and stream_to_event_list to the generic context API
  cudax/include/cuda/experimental/__stf/internal/context.cuh
Labels: stf

#4319 Remove invalid single `#` in builtin.h
  libcudacxx/include/cuda/std/__cccl/builtin.h
Labels: backport branch/2.8.x, backport branch/3.0.x

#4064 Add multi-dimensional support to block_reduce routines.
  python/cuda_cooperative/cuda/cooperative/experimental/_common.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_reduce.py
  python/cuda_cooperative/tests/test_block_reduce.py
Labels: cuda.cooperative

#4315 [STF] green_context affinity test
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/places/affinity_gc.cu
Labels: stf

#4314 [STF] Print a summary of the logical data that were used in a context
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
Labels: stf

#4324 Update PTX `ld/st`
  docs/libcudacxx/ptx/instructions/generated/ld.rst
  docs/libcudacxx/ptx/instructions/generated/st.rst
  libcudacxx/include/cuda/__ptx/instructions/generated/clusterlaunchcontrol.h
  libcudacxx/include/cuda/__ptx/instructions/generated/ld.h
  libcudacxx/include/cuda/__ptx/instructions/generated/st.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_mma.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/clusterlaunchcontrol.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/ld.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/st.h
Labels: 3.0

#4332 Rename `WarpShuffleResult` to `warp_shuffle_result`
  docs/libcudacxx/extended_api/warp/warp_shuffle.rst
  libcudacxx/include/cuda/__warp/warp_shuffle.h
Labels: backport branch/3.0.x

#4340 Disable extended floating-point types for nvc++
  libcudacxx/include/cuda/std/__cccl/extended_data_types.h
Labels: 3.0

#3441 Refactoring `ThreadReduce`
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/specializations/block_reduce_raking_commutative_only.cuh
  cub/cub/detail/array_utils.cuh
  cub/cub/detail/type_traits.cuh
  cub/cub/thread/thread_load.cuh
  cub/cub/thread/thread_operators.cuh
  cub/cub/thread/thread_reduce.cuh
  cub/cub/thread/thread_simd.cuh
  cub/test/thread_reduce/catch2_test_thread_reduce.cu
  cub/test/thread_reduce/catch2_test_thread_reduce_check_sass.cu
  docs/cub/index.rst
  docs/cub/modules.rst
  docs/cub/thread_level.rst
Labels: 3.0

#4374 [STF] Fix an iterator type error with an unordered_multimap
  cudax/include/cuda/experimental/__stf/internal/executable_graph_cache.cuh
Labels: stf

#4373 [STF] Add support for codes which do not allow exceptions
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/utility/cuda_safe_call.cuh
  cudax/include/cuda/experimental/__stf/utility/traits.cuh
  cudax/include/cuda/experimental/__stf/utility/unittest.cuh
Labels: stf

#4380 [STF] Fix task dependencies when using tokens
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
Labels: stf

#4052 Fix autogenerating release notes.
  .github/workflows/release-finalize.yml
Labels: 3.0, backport branch/3.0.x

#4403 [STF] Temporarility disable the algorithm construct
  cudax/include/cuda/experimental/stf.cuh
  cudax/test/stf/CMakeLists.txt
Labels: stf

#4413 [STF] Honor CCCL_DISABLE_NVTX and NVTX_DISABLE in STF
  cudax/include/cuda/experimental/__stf/utility/nvtx.cuh
Labels: stf

#4416 avoid EDG bug by moving diagnostic push & pop out of templates
  libcudacxx/include/cuda/std/__bit/reference.h
  libcudacxx/include/cuda/std/array
  libcudacxx/include/cuda/std/bitset
Labels: nvbug, libcu++, bug

#4352 Fix uninitialized read in local atomic code path.
  libcudacxx/include/cuda/std/__atomic/functions/cuda_local.h
  libcudacxx/test/libcudacxx/cuda/atomics/atomic.uninitialized.pass.cpp
Labels: backport branch/2.8.x, backport branch/3.0.x

#4430 [STF] Simpler token API
  cudax/examples/stf/void_data_interface.cu
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
  cudax/test/stf/dot/sections_2.cu
  cudax/test/stf/freeze/token.cu
  cudax/test/stf/local_stf/legacy_to_stf.cu
  cudax/test/stf/parallel_for/parallel_for_host.cu
  docs/cudax/stf.rst
Labels: stf

#4439 Missing header in `<cuda/bit>`
  libcudacxx/include/cuda/bit
Labels: 3.0

#4444 Enable device assertions in CUDA debug mode
  libcudacxx/include/cuda/std/__cccl/assert.h
Labels: 3.1.0

#4306 [STF] Refactor CUDASTF allocators
  cudax/include/cuda/experimental/__stf/allocators/block_allocator.cuh
  cudax/include/cuda/experimental/__stf/allocators/buddy_allocator.cuh
  cudax/include/cuda/experimental/__stf/allocators/cached_allocator.cuh
  cudax/include/cuda/experimental/__stf/allocators/pooled_allocator.cuh
Labels: stf

#4445 Add PTX `elect.sync`
  docs/libcudacxx/ptx/instructions.rst
  docs/libcudacxx/ptx/instructions/elect_sync.rst
  docs/libcudacxx/ptx/instructions/generated/elect_sync.rst
  libcudacxx/include/cuda/__ptx/instructions/elect_sync.h
  libcudacxx/include/cuda/__ptx/instructions/generated/elect_sync.h
  libcudacxx/include/cuda/ptx
  libcudacxx/test/libcudacxx/cuda/ptx/generated/elect_sync.h
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.elect.sync.compile.pass.cpp
Labels: 3.1.0

#4456 Improve `_CCCL_ASSUME`
  docs/cccl/development/macro.rst
  libcudacxx/include/cuda/std/__bit/integral.h
  libcudacxx/include/cuda/std/__cccl/attributes.h
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/include/cuda/std/detail/__annotated_ptr
  libcudacxx/test/libcudacxx/libcxx/macros/assume_attribute.pass.cpp
Labels: 3.1.0

#4484 `cuda::bitmask` should have a default type
  docs/libcudacxx/extended_api/bit/bitmask.rst
  libcudacxx/include/cuda/__bit/bitmask.h
Labels: 3.1.0

#4451 Use `cudaStream_t` for `thrust::device.on(...)`.
  cub/benchmarks/nvbench_helper/nvbench_helper/nvbench_helper.cuh
  thrust/testing/cuda/stream_wrapper.cu
  thrust/thrust/system/cuda/detail/par.h
Labels: backport branch/3.0.x

#4499 Fix `__nv_pure__` compatibility
  libcudacxx/include/cuda/std/__cccl/attributes.h
Labels: 3.1.0, CI Passed

#4494 `__has_unique_object_representations` is supported by MSVC
  libcudacxx/include/cuda/std/__cccl/builtin.h
Labels: 3.1.0, CI Passed

#3439 c.parallel: device wrappers as code, not format strings
  c/parallel/CMakeLists.txt
  c/parallel/src/jit_templates/CMakeLists.txt
  c/parallel/src/jit_templates/README.md
  c/parallel/src/jit_templates/jit_entry.h
  c/parallel/src/jit_templates/mappings/iterator.h
  c/parallel/src/jit_templates/mappings/operation.h
  c/parallel/src/jit_templates/mappings/type_info.h
  c/parallel/src/jit_templates/template_post.h.in
  c/parallel/src/jit_templates/template_pre.h.in
  c/parallel/src/jit_templates/templates/input_iterator.h
  c/parallel/src/jit_templates/templates/operation.h
  c/parallel/src/jit_templates/templates/output_iterator.h
  c/parallel/src/jit_templates/traits.h
  c/parallel/src/reduce.cu
Labels: feature request

#4485 Add `ceil_ilog2`
  docs/libcudacxx/extended_api/math/ilog.rst
  libcudacxx/include/cuda/__cmath/ilog.h
  libcudacxx/test/libcudacxx/cuda/cmath/ilog.pass.cpp
Labels: 3.1.0, CI Passed

#4490 [STF] Support dynamic dependencies in the cuda_kernel construct and document cuda_kernel
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/cuda_kernel_scope.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/interface/cuda_kernel_chain-add_deps.cu
  docs/cudax/stf.rst
Labels: stf

#4521 Replace `cub::internal` with `cub::detail`
  cub/cub/agent/agent_rle.cuh
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/block_scan.cuh
  cub/cub/block/specializations/block_scan_raking.cuh
  cub/cub/thread/thread_operators.cuh
  cub/cub/thread/thread_reduce.cuh
  cub/cub/thread/thread_scan.cuh
  cub/cub/thread/thread_simd.cuh
Labels: 3.1.0

#4355 [Thrust] `reduce_into`
  thrust/testing/reduce.cu
  thrust/testing/reduce_into.cu
  thrust/thrust/detail/reduce.inl
  thrust/thrust/reduce.h
  thrust/thrust/system/cuda/detail/reduce.h
  thrust/thrust/system/detail/generic/reduce.h
  thrust/thrust/system/detail/generic/reduce.inl
Labels: thrust
