Repository NVIDIA/cccl, pull requests merged in 2025-03, with the labels that each got.

#3974 [PTX] Add `st`, `ld` instructions
  docs/libcudacxx/ptx/instructions.rst
  docs/libcudacxx/ptx/instructions/generated/ld.rst
  docs/libcudacxx/ptx/instructions/generated/st.rst
  docs/libcudacxx/ptx/instructions/ld.rst
  docs/libcudacxx/ptx/instructions/st.rst
  libcudacxx/include/cuda/__ptx/instructions/generated/ld.h
  libcudacxx/include/cuda/__ptx/instructions/generated/st.h
  libcudacxx/include/cuda/__ptx/instructions/ld.h
  libcudacxx/include/cuda/__ptx/instructions/st.h
  libcudacxx/include/cuda/ptx
  libcudacxx/test/libcudacxx/cuda/ptx/generated/ld.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/st.h
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.ld.compile.pass.cpp
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.st.compile.pass.cpp
Labels: 3.0

#3988 Fix definition of universal_host_pinned_memory_resource
  thrust/testing/universal_memory.cu
  thrust/thrust/system/cpp/memory_resource.h
  thrust/thrust/system/omp/memory_resource.h
  thrust/thrust/system/tbb/memory_resource.h
Labels: thrust, breaking

#3228 Optimize and cleanup `cuda::std::rotl` and `cuda::std::rotr`
  docs/libcudacxx/standard_api/numerics_library/bit.rst
  libcudacxx/include/cuda/std/__bit/rotate.h
Labels: 3.0

#3963 Implement more of cmath
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/include/cuda/std/__cmath/gamma.h
  libcudacxx/include/cuda/std/__cmath/hyperbolic_functions.h
  libcudacxx/include/cuda/std/__cmath/hypot.h
  libcudacxx/include/cuda/std/__cmath/inverse_hyperbolic_functions.h
  libcudacxx/include/cuda/std/__cmath/inverse_trigonometric_functions.h
  libcudacxx/include/cuda/std/__cmath/nvbf16.h
  libcudacxx/include/cuda/std/__cmath/nvfp16.h
  libcudacxx/include/cuda/std/__cmath/trigonometric_functions.h
  libcudacxx/include/cuda/std/__internal/features.h
  libcudacxx/include/cuda/std/detail/libcxx/include/cmath
  libcudacxx/include/cuda/std/detail/libcxx/include/complex
  libcudacxx/test/libcudacxx/std/numerics/c.math/comparison.h
  libcudacxx/test/libcudacxx/std/numerics/c.math/exponential_functions.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/fp_abs.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/fp_min_max.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/fp_traits.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/gamma.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/hyperbolic_functions.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/hypot.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/inverse_hyperbolic_functions.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/inverse_trigonometric_functions.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/lerp.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/logarithms.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/roots.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/rounding.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/c.math/trigonometric_functions.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/complex.number/cases.h
Labels: feature request, libcu++, 3.0

#3992 Assert offset type in `DispatchScan[ByKey]` to be unsigned and at least 4 bytes
  cub/benchmarks/bench/scan/exclusive/by_key.cu
  cub/cub/device/dispatch/dispatch_scan.cuh
  cub/cub/device/dispatch/dispatch_scan_by_key.cuh
Labels: cub, breaking

#3821 Drop deprecated CUB macros
  cub/cub/thread/thread_search.cuh
  cub/cub/util_macro.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
Labels: cub, breaking

#4007 Drop deprecated warp/block algo specializations
  cub/cub/block/specializations/block_histogram_atomic.cuh
  cub/cub/block/specializations/block_histogram_sort.cuh
  cub/cub/block/specializations/block_reduce_raking.cuh
  cub/cub/block/specializations/block_reduce_raking_commutative_only.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/block/specializations/block_scan_raking.cuh
  cub/cub/block/specializations/block_scan_warp_scans.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/specializations/warp_scan_smem.cuh
Labels: cub, breaking

#4009 Drop remaining 2.8-deprecated entities
  cub/cub/device/dispatch/tuning/tuning_adjacent_difference.cuh
  cub/cub/device/dispatch/tuning/tuning_merge_sort.cuh
  cub/cub/device/dispatch/tuning/tuning_radix_sort.cuh
  cub/cub/device/dispatch/tuning/tuning_reduce.cuh
  cub/cub/device/dispatch/tuning/tuning_scan.cuh
  cub/cub/device/dispatch/tuning/tuning_scan_by_key.cuh
  cub/cub/device/dispatch/tuning/tuning_segmented_sort.cuh
  cub/cub/device/dispatch/tuning/tuning_unique_by_key.cuh
  cub/cub/thread/thread_load.cuh
  cub/cub/util_allocator.cuh
  cub/cub/util_type.cuh
Labels: cub, breaking

#3973 Use cuda::std::array in histogram APIs
  cub/benchmarks/bench/histogram/even.cu
  cub/benchmarks/bench/histogram/multi/even.cu
  cub/benchmarks/bench/histogram/multi/range.cu
  cub/benchmarks/bench/histogram/range.cu
  cub/cub/device/device_histogram.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/test/catch2_test_device_histogram.cu
Labels: cub

#1964 Test tuple of iterator reference assignment
  thrust/testing/tuple.cu
Labels: thrust

#3941 Extended `<cuda/bit>` operations: `bitfield_insert`, `bitfield_extract`, `bit_reverse`, `bitmask`
  docs/libcudacxx/extended_api.rst
  docs/libcudacxx/extended_api/bit.rst
  docs/libcudacxx/extended_api/bit/bit_reverse.rst
  docs/libcudacxx/extended_api/bit/bitfield_extract.rst
  docs/libcudacxx/extended_api/bit/bitfield_insert.rst
  docs/libcudacxx/extended_api/bit/bitmask.rst
  libcudacxx/include/cuda/__bit/bit_reverse.h
  libcudacxx/include/cuda/__bit/bitfield.h
  libcudacxx/include/cuda/__bit/bitmask.h
  libcudacxx/include/cuda/bit
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/test/libcudacxx/cuda/bit/bit_reverse.pass.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.fail.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.pass.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitmask.pass.cpp
Labels: 3.0

#4023 Fix `cuda::std::assume_aligned` assertion
  libcudacxx/include/cuda/std/__memory/assume_aligned.h
Labels: 3.0

#3907 Safe warp shuffle operations
  docs/libcudacxx/extended_api.rst
  docs/libcudacxx/extended_api/warp.rst
  docs/libcudacxx/extended_api/warp/warp_shuffle.rst
  docs/libcudacxx/ptx/instructions/manual/shfl_sync.rst
  docs/libcudacxx/ptx/instructions/shfl_sync.rst
  libcudacxx/include/cuda/__ptx/instructions/shfl_sync.h
  libcudacxx/include/cuda/__warp/warp_shuffle.h
  libcudacxx/include/cuda/warp
  libcudacxx/test/libcudacxx/cuda/warp/warp_shuffle.pass.cpp
Labels: 3.0

#4047 Fix definition of `<cuda/std/numbers>`
  docs/libcudacxx/standard_api/numerics_library/numbers.rst
  libcudacxx/include/cuda/std/__cccl/dialect.h
  libcudacxx/include/cuda/std/__cccl/execution_space.h
  libcudacxx/include/cuda/std/numbers
  libcudacxx/test/libcudacxx/std/language.support/support.srcloc/general.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/numbers/defined.pass.cpp
  libcudacxx/test/libcudacxx/std/numerics/numbers/value.pass.cpp
  libcudacxx/test/support/test_macros.h
  thrust/thrust/optional.h
Labels: bug: functional

#4016 [STF] Improve nvtx_range API
  cudax/examples/stf/cfd.cu
  cudax/examples/stf/linear_algebra/06-pdgemm.cu
  cudax/examples/stf/linear_algebra/07-cholesky.cu
  cudax/examples/stf/linear_algebra/07-potri.cu
  cudax/include/cuda/experimental/__stf/internal/dot.cuh
  cudax/include/cuda/experimental/__stf/utility/nvtx.cuh
  cudax/test/stf/examples/07-cholesky-redux.cu
  cudax/test/stf/examples/07-cholesky-unified.cu
  cudax/test/stf/gnu/06-pdgemm.cpp
  cudax/test/stf/gnu/07-cholesky.cpp
  cudax/test/stf/local_stf/legacy_to_stf.cu
Labels: stf

#4024 [STF] Fix error in link_check and a bunch of other warnings
  cudax/examples/stf/linear_algebra/07-cholesky.cu
  cudax/examples/stf/linear_algebra/07-potri.cu
  cudax/include/cuda/experimental/__stf/places/exec/host/callback_queues.cuh
  cudax/test/stf/cuda-samples/3_CUDA_Features/jacobiCudaGraphs/jacobi.cu
  cudax/test/stf/examples/07-cholesky-redux.cu
  cudax/test/stf/examples/07-cholesky-unified.cu
Labels: stf

#4045 Fix PTX `ld/st`
  docs/libcudacxx/ptx/instructions/generated/ld.rst
  docs/libcudacxx/ptx/instructions/generated/st.rst
  libcudacxx/include/cuda/__ptx/instructions/generated/ld.h
  libcudacxx/include/cuda/__ptx/instructions/generated/st.h
  libcudacxx/include/cuda/__ptx/ptx_helper_functions.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/ld.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/st.h
Labels: 3.0

#4087 Allow zero size bitmask
  docs/libcudacxx/extended_api/bit/bitfield_extract.rst
  docs/libcudacxx/extended_api/bit/bitfield_insert.rst
  docs/libcudacxx/extended_api/bit/bitmask.rst
  libcudacxx/include/cuda/__bit/bitfield.h
  libcudacxx/include/cuda/__bit/bitmask.h
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.fail.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.pass.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitmask.pass.cpp
Labels: 3.0

#4111 [thrust, docs] Use the variadic overload of `make_zip_iterator` in the `zip_iterator` docs
  thrust/thrust/iterator/zip_iterator.h
Labels: thrust

#4031 Deprecate and Replace `cub::BFE`
  cub/cub/block/radix_rank_sort_operations.cuh
  cub/cub/util_ptx.cuh
  docs/libcudacxx/extended_api/bit/bitfield_extract.rst
  docs/libcudacxx/extended_api/bit/bitfield_insert.rst
  docs/libcudacxx/extended_api/bit/bitmask.rst
  libcudacxx/include/cuda/__bit/bitfield.h
  libcudacxx/include/cuda/__bit/bitmask.h
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.fail.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitfield.pass.cpp
  libcudacxx/test/libcudacxx/cuda/bit/bitmask.pass.cpp
Labels: 3.0

#4028 Add multi-dimensional support to block_merge_sort.merge_sort_keys()
  python/cuda_cooperative/cuda/cooperative/experimental/_types.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_merge_sort.py
  python/cuda_cooperative/tests/test_block_merge_sort.py
Labels: 3.0

#4035 Add multi-dimensional support to block_radix_sort routines.
  python/cuda_cooperative/cuda/cooperative/experimental/_common.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_radix_sort.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_scan.py
  python/cuda_cooperative/tests/test_block_radix_sort.py
  python/cuda_cooperative/tests/test_common.py
Labels: 3.0

#4138 Add missing `explicit` conversion constructor to `cuda::std::aligned_accessor`
  libcudacxx/include/cuda/std/__mdspan/aligned_accessor.h
  libcudacxx/test/libcudacxx/std/containers/views/mdspan/mdspan.aligned_accessor/aligned_accessor.alignment.fail.cpp
  libcudacxx/test/libcudacxx/std/containers/views/mdspan/mdspan.aligned_accessor/aligned_accessor.explicit.fail.cpp
  libcudacxx/test/libcudacxx/std/containers/views/mdspan/mdspan.aligned_accessor/aligned_accessor.pass.cpp
Labels: 3.0

#4100 Implement `cuda::ilog2` and `cuda::ilog10`
  docs/libcudacxx/extended_api/math.rst
  docs/libcudacxx/extended_api/math/ilog.rst
  libcudacxx/include/cuda/__cmath/ilog.h
  libcudacxx/include/cuda/cmath
  libcudacxx/test/libcudacxx/cuda/cmath/ilog.pass.cpp
Labels: 3.0

#4146 Fix small typo in `ilog` documentation
  docs/libcudacxx/extended_api/math/ilog.rst
Labels: 3.0

#4065 Adds support for large number of buffers to `DeviceMemcpy::Batched`
  cub/benchmarks/bench/copy/memcpy.cu
  cub/cub/device/device_copy.cuh
  cub/cub/device/device_memcpy.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/test/catch2_test_device_memcpy_batched.cu
  cub/test/catch2_test_device_memcpy_batched_common.cuh
Labels: breaking

#4137 Provide `restrict` accessor
  docs/libcudacxx/extended_api.rst
  docs/libcudacxx/extended_api/mdspan.rst
  docs/libcudacxx/extended_api/mdspan/restrict_accessor.rst
  libcudacxx/include/cuda/__mdspan/restrict_accessor.h
  libcudacxx/include/cuda/__mdspan/restrict_mdspan.h
  libcudacxx/include/cuda/mdspan
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.restrict.conversion.pass.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.restrict.functional.pass.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.restrict.pass.cpp
Labels: 3.0

#4157 [STF] Repair task_fence implementation with graph_ctx
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/graph/graph_data_interface.cuh
  cudax/include/cuda/experimental/__stf/graph/graph_task.cuh
  cudax/include/cuda/experimental/__stf/graph/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/internal/acquire_release.cuh
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/cuda_kernel_scope.cuh
  cudax/include/cuda/experimental/__stf/internal/frozen_logical_data.cuh
  cudax/include/cuda/experimental/__stf/internal/host_launch_scope.cuh
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
  cudax/include/cuda/experimental/__stf/internal/msir.cuh
  cudax/include/cuda/experimental/__stf/internal/task.cuh
  cudax/include/cuda/experimental/__stf/internal/task_state.cuh
  cudax/include/cuda/experimental/__stf/stream/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_ctx.cuh
Labels: stf

#4165 Replace CUB `util_arch.cuh` macros with `inline constexpr` variables
  cub/cub/agent/agent_batch_memcpy.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_radix_sort_upsweep.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/single_pass_scan_operators.cuh
  cub/cub/block/block_exchange.cuh
  cub/cub/block/block_load.cuh
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/block_raking_layout.cuh
  cub/cub/block/block_scan.cuh
  cub/cub/block/block_shuffle.cuh
  cub/cub/block/block_store.cuh
  cub/cub/block/specializations/block_reduce_raking.cuh
  cub/cub/block/specializations/block_reduce_raking_commutative_only.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/block/specializations/block_scan_warp_scans.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/device/dispatch/kernels/radix_sort.cuh
  cub/cub/util_arch.cuh
  cub/cub/util_cpp_dialect.cuh
  cub/cub/util_device.cuh
  cub/cub/util_ptx.cuh
  cub/cub/warp/specializations/warp_exchange_shfl.cuh
  cub/cub/warp/specializations/warp_exchange_smem.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/specializations/warp_scan_smem.cuh
  cub/cub/warp/warp_exchange.cuh
  cub/cub/warp/warp_load.cuh
  cub/cub/warp/warp_merge_sort.cuh
  cub/cub/warp/warp_reduce.cuh
  cub/cub/warp/warp_scan.cuh
  cub/cub/warp/warp_store.cuh
  cub/test/catch2_test_warp_exchange.cuh
  cub/test/catch2_test_warp_load.cu
  cub/test/catch2_test_warp_mask.cu
  cub/test/catch2_test_warp_reduce.cu
  cub/test/catch2_test_warp_scan.cu
  cub/test/catch2_test_warp_store.cu
Labels: 3.0

#4186 Fix `not_fn`
  docs/repo.toml
  libcudacxx/include/cuda/std/__functional/not_fn.h
Labels: backport branch/3.0.x

#4202 [backport/3.0] Replace CUB util_arch.cuh macros with inline constexpr variables #4165
  cub/cub/agent/agent_batch_memcpy.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_radix_sort_upsweep.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/single_pass_scan_operators.cuh
  cub/cub/block/block_exchange.cuh
  cub/cub/block/block_load.cuh
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/block_raking_layout.cuh
  cub/cub/block/block_scan.cuh
  cub/cub/block/block_shuffle.cuh
  cub/cub/block/block_store.cuh
  cub/cub/block/specializations/block_reduce_raking.cuh
  cub/cub/block/specializations/block_reduce_raking_commutative_only.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/block/specializations/block_scan_warp_scans.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/device/dispatch/kernels/radix_sort.cuh
  cub/cub/util_arch.cuh
  cub/cub/util_device.cuh
  cub/cub/util_ptx.cuh
  cub/cub/warp/specializations/warp_exchange_shfl.cuh
  cub/cub/warp/specializations/warp_exchange_smem.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/specializations/warp_scan_smem.cuh
  cub/cub/warp/warp_exchange.cuh
  cub/cub/warp/warp_load.cuh
  cub/cub/warp/warp_merge_sort.cuh
  cub/cub/warp/warp_reduce.cuh
  cub/cub/warp/warp_scan.cuh
  cub/cub/warp/warp_store.cuh
  cub/test/catch2_test_warp_exchange.cuh
  cub/test/catch2_test_warp_load.cu
  cub/test/catch2_test_warp_mask.cu
  cub/test/catch2_test_warp_reduce.cu
  cub/test/catch2_test_warp_scan.cu
  cub/test/catch2_test_warp_store.cu
Labels: 3.0

#3686 Host/Device accessors for `mdspan`
  docs/libcudacxx/extended_api/mdspan.rst
  docs/libcudacxx/extended_api/mdspan/host_device_accessor.rst
  libcudacxx/include/cuda/__mdspan/host_device_accessor.h
  libcudacxx/include/cuda/__mdspan/host_device_mdspan.h
  libcudacxx/include/cuda/mdspan
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.conversion.pass.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.relation.fail.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/accessor.submdspan.pass.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/device_accessor.fail.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/host_accessor.fail.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/host_accessor.runfail.cpp
  libcudacxx/test/libcudacxx/cuda/mdspan/host_device_accessor.pass.cpp
Labels: 3.0

#4220 Improve host/device mdspan documentation
  docs/libcudacxx/extended_api/mdspan/host_device_accessor.rst
Labels: 3.0

#4231 Fix typos in cuda mdspan documentation
  docs/libcudacxx/extended_api/mdspan/host_device_accessor.rst
Labels: 3.0

#4237 Document deprecations from #4165
  docs/cccl/3.0_migration_guide.rst
Labels: backport branch/3.0.x

#3884 Add new `WarpReduce` overloadings
  c2h/include/c2h/check_results.cuh
  c2h/include/c2h/operator.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/detail/type_traits.cuh
  cub/cub/device/dispatch/dispatch_for.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/warp_reduce.cuh
  cub/test/warp/catch2_test_warp_reduce.cu
  cub/test/warp/catch2_test_warp_segmented_reduce.cu
Labels: 3.0

#3857 [STF] Enable NVHPC in CUDASTF CI
  cudax/examples/CMakeLists.txt
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/parallel_for_scope.cuh
  cudax/include/cuda/experimental/__stf/places/places.cuh
  cudax/include/cuda/experimental/stf.cuh
  cudax/test/CMakeLists.txt
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/parallel_for/parallel_for_host.cu
  cudax/test/stf/parallel_for/test_parallel_for.cu
Labels: stf

#4260 [STF] fix type issues in the multi-GPU CG test
  cudax/test/stf/cuda-samples/4_CUDA_Libraries/conjugateGradientMultiDeviceCG/conjugateGradientMultiDeviceCG_custf.cu
Labels: stf

#4278 change version check in `type_list.h` so that *NO* clang-19.X compilers try to use pack indexing
  libcudacxx/include/cuda/std/__type_traits/type_list.h
Labels: backport branch/3.0.x

#4282 Fix internal `shfl` check
  libcudacxx/include/cuda/__ptx/instructions/shfl_sync.h
Labels: 3.0

#4279 tweak the cccl compiler version check macros to better agree with intuition
  docs/cccl/development/macro.rst
  libcudacxx/include/cuda/std/__cccl/compiler.h
  libcudacxx/include/cuda/std/__cccl/preprocessor.h
Labels: backport branch/3.0.x
