Repository NVIDIA/cccl, pull requests merged in 2025-08, with the labels that each got.

#5414 Move TMA barrier in DeviceTransform into dynamic SMEM
  cub/cub/device/dispatch/dispatch_transform.cuh
  cub/cub/device/dispatch/kernels/transform.cuh
  cub/cub/device/dispatch/tuning/tuning_transform.cuh
  cub/test/catch2_test_device_transform.cu
Labels: backport branch/3.0.x, backport branch/3.1.x

#5456 Fix grid dependency sync in cub::DeviceMergeSort
  cub/cub/agent/agent_merge_sort.cuh
  cub/cub/device/dispatch/kernels/merge_sort.cuh
Labels: backport branch/2.8.x, backport branch/3.0.x, backport branch/3.1.x

#5267 Integer Add with overflow checking
  docs/libcudacxx/extended_api/numeric.rst
  docs/libcudacxx/extended_api/numeric/add_overflow.rst
  docs/libcudacxx/extended_api/numeric/overflow_result.rst
  libcudacxx/include/cuda/__numeric/add_overflow.h
  libcudacxx/include/cuda/__numeric/overflow_cast.h
  libcudacxx/include/cuda/numeric
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/test/libcudacxx/cuda/numeric/overflow.arithmetic/add_overflow.pass.cpp
Labels: CI 100%, 3.2.0

#5418 fix `NV_TARGET` typos
  libcudacxx/include/cuda/std/__cccl/ptx_isa.h
  libcudacxx/include/nv/detail/__target_macros
Labels: 3.2.0

#5317 CUB - Add internal thread and warp utils (Split `WarpReduce` PR)
  c2h/include/c2h/check_results.cuh
  cub/cub/detail/type_traits.cuh
  cub/cub/thread/thread_operators.cuh
  cub/cub/thread/thread_reduce.cuh
  cub/cub/thread/thread_simd.cuh
  cub/cub/warp/warp_utils.cuh
Labels: 3.2.0

#5473 [STF] Cleanup for_each_batched.cuh
  cudax/include/cuda/experimental/__stf/internal/for_each_batched.cuh
Labels: stf

#5474 [Backport branch/3.1.x] `NV_TARGET` and `cuda::ptx` for CTK 13
  docs/libcudacxx/ptx/instructions/generated/clusterlaunchcontrol.rst
  docs/libcudacxx/ptx/instructions/generated/cp_async_bulk_multicast.rst
  docs/libcudacxx/ptx/instructions/generated/cp_async_bulk_tensor.rst
  docs/libcudacxx/ptx/instructions/generated/cp_async_bulk_tensor_gather_scatter.rst
  docs/libcudacxx/ptx/instructions/generated/cp_async_bulk_tensor_multicast.rst
  docs/libcudacxx/ptx/instructions/generated/ld.rst
  docs/libcudacxx/ptx/instructions/generated/st.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_alloc.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_commit.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_cp.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_fence.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_ld.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_mma.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_mma_ws.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_shift.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_st.rst
  docs/libcudacxx/ptx/instructions/generated/tcgen05_wait.rst
  docs/libcudacxx/ptx/instructions/generated/tensormap_replace.rst
  libcudacxx/include/cuda/__ptx/instructions/generated/clusterlaunchcontrol.h
  libcudacxx/include/cuda/__ptx/instructions/generated/cp_async_bulk_multicast.h
  libcudacxx/include/cuda/__ptx/instructions/generated/cp_async_bulk_tensor.h
  libcudacxx/include/cuda/__ptx/instructions/generated/cp_async_bulk_tensor_gather_scatter.h
  libcudacxx/include/cuda/__ptx/instructions/generated/cp_async_bulk_tensor_multicast.h
  libcudacxx/include/cuda/__ptx/instructions/generated/ld.h
  libcudacxx/include/cuda/__ptx/instructions/generated/st.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_alloc.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_commit.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_cp.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_fence.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_ld.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_mma.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_mma_ws.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_shift.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_st.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tcgen05_wait.h
  libcudacxx/include/cuda/__ptx/instructions/generated/tensormap_replace.h
  libcudacxx/include/cuda/std/__cccl/ptx_isa.h
  libcudacxx/include/nv/detail/__target_macros
  libcudacxx/include/nv/target
  libcudacxx/test/libcudacxx/cuda/ptx/generated/clusterlaunchcontrol.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/cp_async_bulk_multicast.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/cp_async_bulk_tensor.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/cp_async_bulk_tensor_gather_scatter.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/cp_async_bulk_tensor_multicast.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/ld.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/st.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_alloc.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_commit.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_cp.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_fence.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_ld.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_mma.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_mma_ws.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_shift.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_st.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tcgen05_wait.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/tensormap_replace.h
Labels: 3.0, backport branch/3.0.x, 3.1.0

#5475 [STF] Improve how we ignore void interface (tokens) arguments in prototypes
  cudax/examples/stf/void_data_interface.cu
  cudax/include/cuda/experimental/__stf/graph/graph_task.cuh
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/host_launch_scope.cuh
  cudax/include/cuda/experimental/__stf/internal/parallel_for_scope.cuh
  cudax/include/cuda/experimental/__stf/internal/slice.cuh
  cudax/include/cuda/experimental/__stf/internal/void_interface.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_task.cuh
  cudax/include/cuda/experimental/__stf/utility/core.cuh
  cudax/include/cuda/experimental/__stf/utility/traits.cuh
  cudax/test/stf/dot/sections_2.cu
  cudax/test/stf/parallel_for/parallel_for_host.cu
Labels: stf

#5489 Add `SM_110a` for non-supporting compilers
  libcudacxx/include/nv/detail/__target_macros
Labels: 3.2.0, backport branch/3.1.x

#5534 [libcu++] Rename resource_ref to match the new async by default naming
  cudax/include/cuda/experimental/__container/async_buffer.cuh
  cudax/include/cuda/experimental/__memory_resource/any_resource.cuh
  cudax/test/memory_resource/any_resource.cu
  docs/libcudacxx/extended_api/memory_resource.rst
  docs/libcudacxx/extended_api/memory_resource/resource.rst
  docs/libcudacxx/extended_api/memory_resource/resource_ref.rst
  libcudacxx/include/cuda/__memory_resource/resource_ref.h
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/allocate.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/construction.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/conversion.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/equality.fail.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/equality.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/inheritance.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/properties.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/allocate.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/construction.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/conversion.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/equality.fail.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/equality.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/inheritance.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/resource_ref/properties.pass.cpp
Labels: backport branch/3.1.x

#5536 [CUDAX] Rename type-erased memory resource wrappers
  cudax/include/cuda/experimental/__container/async_buffer.cuh
  cudax/include/cuda/experimental/__container/uninitialized_async_buffer.cuh
  cudax/include/cuda/experimental/__container/uninitialized_buffer.cuh
  cudax/include/cuda/experimental/__execution/env.cuh
  cudax/include/cuda/experimental/__memory_resource/any_resource.cuh
  cudax/include/cuda/experimental/__memory_resource/shared_resource.cuh
  cudax/test/containers/async_buffer/copy.cu
  cudax/test/containers/async_buffer/test_resources.h
  cudax/test/execution/env.cu
  cudax/test/memory_resource/any_async_resource.cu
  cudax/test/memory_resource/any_resource.cu
  cudax/test/memory_resource/device_memory_resource.cu
  cudax/test/memory_resource/managed_memory_resource.cu
  cudax/test/memory_resource/pinned_memory_resource.cu
  cudax/test/memory_resource/shared_resource.cu
  docs/cudax/memory_resource.rst
Labels: backport branch/3.1.x

#5543 Only download wheels artifacts for release
  .github/workflows/release-wheels.yml
Labels: 3.2.0

#5643 [STF] make get_owning_container_of local to a class
  cudax/include/cuda/experimental/__stf/internal/parallel_for_scope.cuh
Labels: stf

#5645 [STF] Replace task dep's as_read_mode by a more general as_mode
  cudax/include/cuda/experimental/__stf/internal/hooks.cuh
  cudax/include/cuda/experimental/__stf/internal/task_dep.cuh
Labels: stf

#5652 Fixes `thrust::unique` for non-const `equality_op`
  cub/cub/agent/agent_select_if.cuh
  thrust/testing/cuda/unique.cu
Labels: backport branch/3.1.x

#5695 Fix backslashes in blocked doxygen alias in CUB docs
  cub/cub/block/block_load.cuh
  docs/_ext/auto_api_generator.py
  docs/cub/Doxyfile
Labels: doc, area: docs
