Repository NVIDIA/cccl, pull requests merged in 2025-07, with the labels that each got.

#5117 Fix unqualified call to `__unwrap_iter`
  libcudacxx/include/cuda/std/__algorithm/copy.h
  libcudacxx/include/cuda/std/__algorithm/copy_backward.h
Labels: backport branch/3.0.x

#5037 `cuda::` pointer utilities
  docs/libcudacxx/extended_api.rst
  docs/libcudacxx/extended_api/memory.rst
  docs/libcudacxx/extended_api/memory/align_down.rst
  docs/libcudacxx/extended_api/memory/align_up.rst
  docs/libcudacxx/extended_api/memory/is_aligned.rst
  docs/libcudacxx/extended_api/memory/ptr_rebind.rst
  libcudacxx/include/cuda/__memory/align_down.h
  libcudacxx/include/cuda/__memory/align_up.h
  libcudacxx/include/cuda/__memory/is_aligned.h
  libcudacxx/include/cuda/__memory/ptr_rebind.h
  libcudacxx/include/cuda/memory
  libcudacxx/include/cuda/std/__memory/align.h
  libcudacxx/include/cuda/std/__memory/runtime_assume_aligned.h
  libcudacxx/test/libcudacxx/cuda/memory/align_down.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory/align_down.runfail.cpp
  libcudacxx/test/libcudacxx/cuda/memory/align_up.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory/align_up.runfail.cpp
  libcudacxx/test/libcudacxx/cuda/memory/is_aligned.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory/ptr_rebind.pass.cpp
Labels: 3.1.0, CI 100%

#5138 Enhance our deprecation machinery so that we also suppress the right nvcc warnings
  cub/cub/detail/fast_modulo_division.cuh
  cub/test/catch2_test_device_adjacent_difference_substract_right.cu
  cub/test/catch2_test_device_reduce.cu
  cub/test/catch2_test_device_reduce_fp_inf.cu
  cudax/include/cuda/experimental/__execution/epilogue.cuh
  cudax/include/cuda/experimental/__execution/fwd.cuh
  cudax/include/cuda/experimental/__execution/prologue.cuh
  cudax/include/cuda/experimental/__execution/rcvr_ref.cuh
  cudax/include/cuda/experimental/__execution/utility.cuh
  cudax/include/cuda/experimental/__utility/basic_any/basic_any_ref.cuh
  cudax/test/execution/test_stream_context.cu
  docs/cccl/development/macro.rst
  libcudacxx/include/cuda/__fwd/barrier_native_handle.h
  libcudacxx/include/cuda/std/__cccl/compiler.h
  libcudacxx/include/cuda/std/__cccl/diagnostic.h
  libcudacxx/include/cuda/std/__concepts/convertible_to.h
  libcudacxx/include/cuda/std/__concepts/swappable.h
  libcudacxx/include/cuda/std/__functional/unary_negate.h
  libcudacxx/include/cuda/std/__iterator/back_insert_iterator.h
  libcudacxx/include/cuda/std/__iterator/front_insert_iterator.h
  libcudacxx/include/cuda/std/__iterator/insert_iterator.h
  libcudacxx/include/cuda/std/__iterator/istream_iterator.h
  libcudacxx/include/cuda/std/__iterator/istreambuf_iterator.h
  libcudacxx/include/cuda/std/__iterator/ostream_iterator.h
  libcudacxx/include/cuda/std/__iterator/ostreambuf_iterator.h
  libcudacxx/include/cuda/std/__iterator/reverse_iterator.h
  libcudacxx/include/cuda/std/__memory/allocation_guard.h
  libcudacxx/include/cuda/std/__memory/allocator_traits.h
  libcudacxx/include/cuda/std/__memory/pointer_traits.h
  libcudacxx/include/cuda/std/__type_traits/common_reference.h
  libcudacxx/include/cuda/std/__type_traits/is_convertible.h
  libcudacxx/include/cuda/std/detail/libcxx/include/chrono
  libcudacxx/include/cuda/std/detail/libcxx/include/variant
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_get.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_structured_bindings.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_tuple_element.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_tuple_size.pass.cpp
  libcudacxx/test/libcudacxx/std/containers/views/mdspan/CustomTestLayouts.h
  libcudacxx/test/support/test_iterators.h
  libcudacxx/test/support/test_macros.h
Labels: backport branch/3.0.x

#5183 Better specify `lane_mask::all_active()` behavior
  docs/libcudacxx/extended_api/warp/lane_mask.rst
  docs/libcudacxx/extended_api/warp/warp_match_all.rst
  docs/libcudacxx/extended_api/warp/warp_shuffle.rst
  libcudacxx/include/cuda/__warp/lane_mask.h
  libcudacxx/include/cuda/__warp/warp_match_all.h
Labels: doc, 3.1.0

#5235 [STF] Keep dependency event names in DOT
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
  cudax/include/cuda/experimental/__stf/stream/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_ctx.cuh
Labels: stf

#5232 [STF] Cleanup how we specify edge type in DOT output
  cudax/include/cuda/experimental/__stf/graph/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/internal/acquire_release.cuh
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/dot.cuh
  cudax/include/cuda/experimental/__stf/internal/frozen_logical_data.cuh
  cudax/include/cuda/experimental/__stf/stream/internal/event_types.cuh
Labels: stf

#5253 Disable assertions for QNX, they do not provide the machinery with their libc
  libcudacxx/include/cuda/std/__cccl/assert.h
Labels: backport branch/3.0.x

#5234 [STF] Separately display freeze and unfreeze operations in DOT
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/context.cuh
  cudax/include/cuda/experimental/__stf/internal/dot.cuh
  cudax/include/cuda/experimental/__stf/internal/frozen_logical_data.cuh
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
Labels: stf

#5264 Add missed specializations of the new aligned vector types to cub
  c2h/generators_vector.cu
  c2h/include/c2h/test_util_vec.h
Labels: backport branch/3.0.x

#5210 Expose Fast Modulo Division in libcu++
  docs/libcudacxx/extended_api/math.rst
  docs/libcudacxx/extended_api/math/fast_mod_div.rst
  libcudacxx/include/cuda/__cmath/fast_modulo_division.h
  libcudacxx/include/cuda/cmath
  libcudacxx/include/cuda/std/__type_traits/make_nbit_int.h
  libcudacxx/test/libcudacxx/cuda/cmath/fast_modulo_division.pass.cpp
Labels: 3.1.0, CI 100%

#5314 CUB - Add internal integer utils and tests (Split `WarpReduce` PR)
  cub/cub/detail/integer_utils.cuh
  cub/test/internal/catch2_test_integer_utils.cu
Labels: 3.2.0

#5307 Skip zero values in `fast_mod_div` unit test
  libcudacxx/test/libcudacxx/cuda/cmath/fast_modulo_division.pass.cpp
Labels: 3.2.0

#5306 Remove mentions of CUDA experimental that sneaked into libcu++
  libcudacxx/include/cuda/__device/all_devices.h
  libcudacxx/include/cuda/__device/arch_traits.h
  libcudacxx/include/cuda/__device/attributes.h
  libcudacxx/include/cuda/__device/device_ref.h
  libcudacxx/include/cuda/__device/physical_device.h
  libcudacxx/include/cuda/__driver/driver_api.h
  libcudacxx/include/cuda/__event/event.h
  libcudacxx/include/cuda/__event/event_ref.h
  libcudacxx/include/cuda/__event/timed_event.h
  libcudacxx/include/cuda/__stream/stream.h
  libcudacxx/include/cuda/__stream/stream_ref.h
  libcudacxx/include/cuda/devices
  libcudacxx/test/libcudacxx/cuda/ccclrt/common/testing.cuh
  libcudacxx/test/libcudacxx/cuda/ccclrt/common/utility.cuh
  libcudacxx/test/libcudacxx/cuda/ccclrt/device/arch_traits.c2h.cu
  libcudacxx/test/libcudacxx/cuda/ccclrt/device/device_smoke.c2h.cu
  libcudacxx/test/libcudacxx/cuda/ccclrt/event/event_smoke.cu
  libcudacxx/test/libcudacxx/cuda/ccclrt/stream/stream_smoke.cu
  libcudacxx/test/libcudacxx/cuda/ccclrt/utility/driver_api.c2h.cu
  libcudacxx/test/libcudacxx/cuda/ccclrt/utility/ensure_current_context.c2h.cu
Labels: backport branch/3.1.x

#5310 [libcu++] Deprecate default stream_ref constructor and fix some few last usages
  cub/cub/device/device_reduce.cuh
  cub/test/catch2_test_env_launch_helper.h
  cudax/include/cuda/experimental/__container/uninitialized_async_buffer.cuh
  cudax/include/cuda/experimental/__stream/device_transform.cuh
  cudax/test/containers/uninitialized_async_buffer.cu
  cudax/test/stream/stream_smoke.cu
  libcudacxx/include/cuda/__stream/stream_ref.h
  libcudacxx/test/libcudacxx/cuda/ccclrt/stream/stream_smoke.cu
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/allocate.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/conversion.pass.cpp
  libcudacxx/test/libcudacxx/cuda/memory_resource/async_resource_ref/inheritance.pass.cpp
  libcudacxx/test/libcudacxx/cuda/stream_ref/stream_ref.constructor.pass.cpp
Labels: backport branch/3.1.x

#4662 Implement cuda.coop striped_to_blocked.
  python/cuda_cccl/cuda/cccl/cooperative/experimental/block/__init__.py
  python/cuda_cccl/cuda/cccl/cooperative/experimental/block/_block_exchange.py
  python/cuda_cccl/tests/cooperative/test_block_exchange.py
Labels: 3.0, cuda.cooperative

#5318 Fix nvrtc when there are more than one CTK include directories available
  libcudacxx/test/libcudacxx/CMakeLists.txt
Labels: backport branch/3.0.x, backport branch/3.1.x

#5359 Diagnose missing `numeric_limits` specialization in `DeviceReduce Min/Max`
  cub/cub/device/device_reduce.cuh
Labels: backport branch/3.1.x

#5362 Suppress clang warnings on vector types in upcoming CTK
  c2h/generators_vector.cu
Labels: backport branch/3.0.x, backport branch/3.1.x

#5364 Add `is_object_from`
  docs/libcudacxx/extended_api/memory.rst
  docs/libcudacxx/extended_api/memory/is_address_from.rst
  libcudacxx/include/cuda/__mdspan/host_device_accessor.h
  libcudacxx/include/cuda/__memory/address_space.h
  libcudacxx/test/libcudacxx/cuda/memory/is_address_from.pass.cpp
  libcudacxx/test/libcudacxx/std/utilities/memory/ptr.align/align.pass.cpp
Labels: 3.2.0

#5363 [Backport 3.1.x] `is_address_from` fixes (#5349)
  docs/libcudacxx/extended_api/memory.rst
  docs/libcudacxx/extended_api/memory/is_address_from.rst
  libcudacxx/include/cuda/__mdspan/host_device_accessor.h
  libcudacxx/include/cuda/__memory/address_space.h
  libcudacxx/test/libcudacxx/cuda/memory/is_address_from.pass.cpp
  libcudacxx/test/libcudacxx/std/utilities/memory/ptr.align/align.pass.cpp
Labels: 3.1.0
