Repository NVIDIA/cccl, pull requests merged in 2025-02, with the labels that each got.

#3638 [Backport 2.8] Deprecate `AgentSegmentFixupPolicy`
  cub/cub/agent/agent_segment_fixup.cuh
Labels: 2.8.0

#3639 remove AgentSegmentFixupPolicy
  cub/cub/agent/agent_segment_fixup.cuh
Labels: 3.0

#3608 Turn `TEST_[HALF|BF]_T` into function-style macros and fix some tests
  c2h/generators.cu
  c2h/include/c2h/extended_types.h
  cub/test/catch2_segmented_sort_helper.cuh
  cub/test/catch2_test_device_histogram.cu
  cub/test/catch2_test_device_radix_sort_keys.cu
  cub/test/catch2_test_device_reduce.cu
  cub/test/catch2_test_device_reduce.cuh
  cub/test/catch2_test_device_reduce_by_key.cu
  cub/test/catch2_test_device_scan.cu
  cub/test/catch2_test_device_scan_by_key.cu
  cub/test/catch2_test_device_segmented_radix_sort_keys.cu
  cub/test/catch2_test_device_segmented_reduce.cu
  cub/test/catch2_test_device_segmented_sort_keys.cu
  cub/test/catch2_test_device_segmented_sort_pairs.cu
  cub/test/test_util.h
  cub/test/thread_reduce/catch2_test_thread_reduce.cu
Labels: backport branch/2.8.x

#3646 [STF] frozen_logical_data::get_access_mode()
  cudax/include/cuda/experimental/__stf/internal/frozen_logical_data.cuh
  cudax/test/stf/freeze/freeze_rw.cu
  docs/cudax/stf.rst
Labels: stf

#3599 Backport to 2.8: Suppress execution checks for vocabulary types (#3578)
  libcudacxx/include/cuda/std/__expected/bad_expected_access.h
  libcudacxx/include/cuda/std/__expected/expected.h
  libcudacxx/include/cuda/std/__expected/expected_base.h
  libcudacxx/include/cuda/std/__expected/unexpected.h
  libcudacxx/include/cuda/std/__memory/construct_at.h
  libcudacxx/include/cuda/std/__utility/exchange.h
  libcudacxx/include/cuda/std/__utility/pair.h
  libcudacxx/include/cuda/std/detail/libcxx/include/optional
  libcudacxx/include/cuda/std/detail/libcxx/include/tuple
  libcudacxx/include/cuda/std/detail/libcxx/include/variant
  libcudacxx/test/libcudacxx/cuda/utilities/expected/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/expected/host_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/optional/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/optional/host_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/forward_as_tuple_interop.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/host_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_get.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_structured_bindings.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_tuple_element.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/tuple/vector_types_tuple_size.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/unexpected/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/unexpected/host_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/utility/pair/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/utility/pair/host_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/utility/pair/interop/pair.assign.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/utility/pair/interop/pair.cons.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/utility/pair/interop/pair.conv.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/variant/device_only_types.pass.cpp
  libcudacxx/test/libcudacxx/cuda/utilities/variant/host_only_types.pass.cpp
  libcudacxx/test/support/host_device_types.h
Labels: backport branch/2.8.x

#3635 Deprecate cub::FpLimits in favor of cuda::std::numeric_limits
  c2h/include/c2h/bfloat16.cuh
  c2h/include/c2h/half.cuh
  cub/cub/util_type.cuh
  cub/test/catch2_test_util_type.cu
Labels: backport branch/2.8.x

#3643 Replaces bool template parameters on `Dispatch*` class templates to use `enum class`
  cub/benchmarks/bench/adjacent_difference/subtract_left.cu
  cub/benchmarks/bench/copy/memcpy.cu
  cub/benchmarks/bench/partition/flagged.cu
  cub/benchmarks/bench/partition/if.cu
  cub/benchmarks/bench/radix_sort/keys.cu
  cub/benchmarks/bench/radix_sort/pairs.cu
  cub/benchmarks/bench/segmented_sort/keys.cu
  cub/benchmarks/bench/select/flagged.cu
  cub/benchmarks/bench/select/if.cu
  cub/benchmarks/bench/select/unique.cu
  cub/benchmarks/bench/transform/common.h
  cub/cub/agent/agent_select_if.cuh
  cub/cub/device/device_adjacent_difference.cuh
  cub/cub/device/device_copy.cuh
  cub/cub/device/device_memcpy.cuh
  cub/cub/device/device_partition.cuh
  cub/cub/device/device_radix_sort.cuh
  cub/cub/device/device_scan.cuh
  cub/cub/device/device_segmented_radix_sort.cuh
  cub/cub/device/device_segmented_sort.cuh
  cub/cub/device/device_select.cuh
  cub/cub/device/device_transform.cuh
  cub/cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/cub/device/dispatch/dispatch_common.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_scan.cuh
  cub/cub/device/dispatch/dispatch_segmented_sort.cuh
  cub/cub/device/dispatch/dispatch_select_if.cuh
  cub/cub/device/dispatch/dispatch_transform.cuh
  cub/test/catch2_test_device_segmented_radix_sort_keys.cu
  cub/test/catch2_test_device_segmented_radix_sort_pairs.cu
  cub/test/catch2_test_device_transform.cu
  thrust/thrust/system/cuda/detail/adjacent_difference.h
  thrust/thrust/system/cuda/detail/async/inclusive_scan.h
  thrust/thrust/system/cuda/detail/copy_if.h
  thrust/thrust/system/cuda/detail/partition.h
  thrust/thrust/system/cuda/detail/remove.h
  thrust/thrust/system/cuda/detail/scan.h
  thrust/thrust/system/cuda/detail/transform.h
Labels: breaking

#3545 Add b200 policies for device.select.if,flagged,unique
  cub/cub/device/dispatch/tuning/tuning_select_if.cuh
Labels: backport branch/2.8.x

#3626 Add b200 tunings for radix_sort.pairs
  cub/cub/device/dispatch/tuning/tuning_radix_sort.cuh
Labels: backport branch/2.8.x

#3670 PTX: mbarrier.{test,try}_wait: Fix return value
  docs/libcudacxx/ptx/instructions/generated/mbarrier_test_wait.rst
  docs/libcudacxx/ptx/instructions/generated/mbarrier_test_wait_parity.rst
  docs/libcudacxx/ptx/instructions/generated/mbarrier_try_wait.rst
  docs/libcudacxx/ptx/instructions/generated/mbarrier_try_wait_parity.rst
  libcudacxx/include/cuda/__ptx/instructions/generated/mbarrier_test_wait.h
  libcudacxx/include/cuda/__ptx/instructions/generated/mbarrier_test_wait_parity.h
  libcudacxx/include/cuda/__ptx/instructions/generated/mbarrier_try_wait.h
  libcudacxx/include/cuda/__ptx/instructions/generated/mbarrier_try_wait_parity.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/mbarrier_test_wait.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/mbarrier_test_wait_parity.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/mbarrier_try_wait.h
  libcudacxx/test/libcudacxx/cuda/ptx/generated/mbarrier_try_wait_parity.h
Labels: backport branch/2.8.x

#3666 Fix issues with nvrtc compilation
  cub/cub/util_cpp_dialect.cuh
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/include/cuda/std/__internal/cpp_dialect.h
  thrust/thrust/detail/config/cpp_dialect.h
Labels: backport branch/2.8.x

#3588 Function-like macros for FP6/BF16 macros
  c2h/generators.cu
  c2h/include/c2h/extended_types.h
  c2h/include/c2h/generators.h
  cmake/header_test.cu.in
  cub/cmake/CubHeaderTesting.cmake
  cub/cub/agent/agent_sub_warp_merge_sort.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/cub/thread/thread_operators.cuh
  cub/cub/thread/thread_reduce.cuh
  cub/cub/thread/thread_search.cuh
  cub/cub/util_type.cuh
  cub/test/catch2_test_block_radix_sort.cu
  docs/cccl_development/macro.rst
  libcudacxx/include/cuda/std/__cccl/extended_data_types.h
  libcudacxx/include/cuda/std/__internal/features.h
  libcudacxx/include/cuda/std/__type_traits/is_extended_floating_point.h
  libcudacxx/include/cuda/std/limits
  libcudacxx/test/libcudacxx/libcxx/macros/extended_data_types.bf16.fail.cpp
  libcudacxx/test/libcudacxx/libcxx/macros/extended_data_types.fp16.fail.cpp
  libcudacxx/test/libcudacxx/libcxx/macros/extended_data_types.pass.cpp
  libcudacxx/test/libcudacxx/libcxx/utilities/meta/meta.unary/meta.unary.cat/is_floating_point.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/is_specialized.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/common.h
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/const_data_members.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/denorm_min.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/digits.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/digits10.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/epsilon.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/has_denorm.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/has_denorm_loss.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/has_infinity.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/has_quiet_NaN.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/has_signaling_NaN.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/infinity.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_bounded.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_exact.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_iec559.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_integer.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_modulo.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/is_signed.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/lowest.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/max.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/max_digits10.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/max_exponent.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/max_exponent10.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/min.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/min_exponent.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/min_exponent10.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/quiet_NaN.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/radix.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/round_error.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/round_style.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/signaling_NaN.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/tinyness_before.pass.cpp
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/traps.pass.cpp
  thrust/testing/cuda/sort.cu
  thrust/thrust/system/cuda/detail/sort.h
Labels: 3.0

#3677 Remove `cub::ArrayWrapper`
  cub/cub/util_type.cuh
Labels: 3.0

#3681 Internalize cub::PolicyWrapper
  cub/cub/device/dispatch/tuning/tuning_scan.cuh
  cub/cub/util_device.cuh
  cub/cub/util_macro.cuh
Labels: 3.0, backport branch/2.8.x

#3679 Deprecate `cub::AliasTemporaries`
  cub/cub/agent/single_pass_scan_operators.cuh
  cub/cub/detail/temporary_storage.cuh
  cub/cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/cub/device/dispatch/dispatch_merge.cuh
  cub/cub/device/dispatch/dispatch_merge_sort.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/device/dispatch/dispatch_reduce_by_key.cuh
  cub/cub/device/dispatch/dispatch_rle.cuh
  cub/cub/device/dispatch/dispatch_scan.cuh
  cub/cub/device/dispatch/dispatch_scan_by_key.cuh
  cub/cub/device/dispatch/dispatch_select_if.cuh
  cub/cub/device/dispatch/dispatch_streaming_reduce.cuh
  cub/cub/device/dispatch/dispatch_three_way_partition.cuh
  cub/cub/device/dispatch/dispatch_unique_by_key.cuh
  cub/cub/util_temporary_storage.cuh
  cub/test/catch2_test_temporary_storage_layout.cu
  cub/test/catch2_test_vsmem.cu
  thrust/thrust/system/cuda/detail/copy_if.h
  thrust/thrust/system/cuda/detail/core/util.h
  thrust/thrust/system/cuda/detail/extrema.h
  thrust/thrust/system/cuda/detail/partition.h
  thrust/thrust/system/cuda/detail/reduce.h
  thrust/thrust/system/cuda/detail/reduce_by_key.h
  thrust/thrust/system/cuda/detail/unique.h
  thrust/thrust/system/cuda/detail/unique_by_key.h
Labels: 3.0, backport branch/2.8.x

#3684 [CUB] Remove pre-c++17 conditions and code
  cub/cmake/CubBuildTargetList.cmake
  cub/cub/detail/nvtx.cuh
  cub/cub/detail/nvtx3.hpp
  cub/cub/detail/type_traits.cuh
  cub/cub/device/dispatch/dispatch_transform.cuh
  cub/cub/device/dispatch/tuning/tuning_transform.cuh
  cub/examples/block/example_block_reduce_dyn_smem.cu
  cub/test/test_util.h
  cub/test/test_warning_suppression.cuh
  cub/test/thread_reduce/catch2_test_thread_reduce.cu
Labels: 3.0

#3683 Internalize cub::KernelConfig
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/util_device.cuh
Labels: 3.0, backport branch/2.8.x

#3675 Remove cugraph-ops from RAPIDS 25.04 builds.
  .github/workflows/build-rapids.yml
  ci/rapids/cuda12.5-conda/devcontainer.json
Labels: backport branch/2.8.x

#3641 replace Int2Type in CUB library
  cub/benchmarks/bench/histogram/even.cu
  cub/benchmarks/bench/histogram/multi/even.cu
  cub/benchmarks/bench/histogram/multi/range.cu
  cub/benchmarks/bench/histogram/range.cu
  cub/cub/agent/agent_histogram.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_reduce.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/agent_scan.cuh
  cub/cub/agent/agent_scan_by_key.cuh
  cub/cub/agent/agent_segmented_radix_sort.cuh
  cub/cub/agent/agent_select_if.cuh
  cub/cub/agent/agent_sub_warp_merge_sort.cuh
  cub/cub/block/block_exchange.cuh
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/block_radix_sort.cuh
  cub/cub/block/specializations/block_reduce_raking.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/block/specializations/block_scan_raking.cuh
  cub/cub/block/specializations/block_scan_warp_scans.cuh
  cub/cub/device/device_histogram.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/grid/grid_even_share.cuh
  cub/cub/thread/thread_load.cuh
  cub/cub/thread/thread_scan.cuh
  cub/cub/thread/thread_store.cuh
  cub/cub/util_ptx.cuh
  cub/cub/util_type.cuh
  cub/cub/warp/specializations/warp_exchange_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/specializations/warp_scan_smem.cuh
  cub/cub/warp/warp_scan.cuh
  cub/test/catch2_test_block_radix_sort.cuh
  cub/test/catch2_test_block_run_length_decode.cu
  cub/test/test_block_radix_rank.cu
Labels: 3.0

#3546 Add b200 policies for cub.device.run_length_encode.encode,non_trivialruns
  cub/cub/device/dispatch/tuning/tuning_run_length_encode.cuh
Labels: backport branch/2.8.x

#3685 Deprecate `cub::RegBoundScaling` and `cub::MemBoundScaling`
  cub/benchmarks/bench/scan/exclusive/base.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_radix_sort_upsweep.cuh
  cub/cub/agent/agent_reduce.cuh
  cub/cub/agent/agent_scan.cuh
  cub/cub/device/dispatch/tuning/tuning_scan.cuh
  cub/cub/util_arch.cuh
Labels: 3.0, backport branch/2.8.x

#3708 Add b200 policies for partition.three_way
  cub/cub/device/dispatch/tuning/tuning_three_way_partition.cuh
Labels: backport branch/2.8.x

#3705 [backport 2.8] Deprecate and replace `Int2Type`
  cub/benchmarks/bench/histogram/even.cu
  cub/benchmarks/bench/histogram/multi/even.cu
  cub/benchmarks/bench/histogram/multi/range.cu
  cub/benchmarks/bench/histogram/range.cu
  cub/cub/agent/agent_histogram.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_reduce.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/agent_scan.cuh
  cub/cub/agent/agent_scan_by_key.cuh
  cub/cub/agent/agent_segment_fixup.cuh
  cub/cub/agent/agent_segmented_radix_sort.cuh
  cub/cub/agent/agent_select_if.cuh
  cub/cub/agent/agent_spmv_orig.cuh
  cub/cub/agent/agent_sub_warp_merge_sort.cuh
  cub/cub/block/block_exchange.cuh
  cub/cub/block/block_radix_rank.cuh
  cub/cub/block/block_radix_sort.cuh
  cub/cub/block/specializations/block_reduce_raking.cuh
  cub/cub/block/specializations/block_reduce_warp_reductions.cuh
  cub/cub/block/specializations/block_scan_raking.cuh
  cub/cub/block/specializations/block_scan_warp_scans.cuh
  cub/cub/device/device_histogram.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/grid/grid_even_share.cuh
  cub/cub/thread/thread_load.cuh
  cub/cub/thread/thread_scan.cuh
  cub/cub/thread/thread_store.cuh
  cub/cub/util_ptx.cuh
  cub/cub/util_type.cuh
  cub/cub/warp/specializations/warp_exchange_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_reduce_smem.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/specializations/warp_scan_smem.cuh
  cub/cub/warp/warp_scan.cuh
  cub/test/catch2_test_block_radix_sort.cuh
  cub/test/catch2_test_block_run_length_decode.cu
  cub/test/test_block_radix_rank.cu
Labels: 2.8.0

#3717 Removes deprecated `Agent*` alias templates in the public namespace
  cub/cub/agent/agent_adjacent_difference.cuh
  cub/cub/agent/agent_histogram.cuh
  cub/cub/agent/agent_merge_sort.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_histogram.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_radix_sort_upsweep.cuh
  cub/cub/agent/agent_reduce.cuh
  cub/cub/agent/agent_reduce_by_key.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/agent_scan.cuh
  cub/cub/agent/agent_scan_by_key.cuh
  cub/cub/agent/agent_segmented_radix_sort.cuh
  cub/cub/agent/agent_sub_warp_merge_sort.cuh
  cub/cub/agent/agent_unique_by_key.cuh
Labels: cub, breaking

#3560 Add b200 tunings for scan.exclusive.by_key
  cub/cub/device/dispatch/tuning/tuning_scan_by_key.cuh
Labels: backport branch/2.8.x

#3723 Minor fix for a regressing tuning in reduce.by_key
  cub/cub/device/dispatch/tuning/tuning_reduce_by_key.cuh
Labels: backport branch/2.8.x

#3691 Fix SM100 histogram tunings
  cub/cub/device/dispatch/tuning/tuning_histogram.cuh
Labels: backport branch/2.8.x

#3724 Remove reduce tunings with no benefit
  cub/cub/device/dispatch/tuning/tuning_reduce.cuh
Labels: backport branch/2.8.x

#3733 fix ::cuda::discard_memory
  cub/cub/util_vsmem.cuh
Labels: 3.0

#3617 Add b200 policies for cub.device.partition.flagged,if
  cub/cub/agent/agent_select_if.cuh
  cub/cub/device/dispatch/dispatch_select_if.cuh
  cub/cub/device/dispatch/tuning/tuning_select_if.cuh
Labels: backport branch/2.8.x

#3559 Add b200 tunings for scan.exclusive.sum
  cub/benchmarks/bench/scan/exclusive/base.cuh
  cub/cub/device/device_scan.cuh
  cub/cub/device/dispatch/dispatch_scan.cuh
  cub/cub/device/dispatch/tuning/tuning_scan.cuh
  thrust/testing/scan.cu
  thrust/thrust/system/cuda/detail/async/inclusive_scan.h
  thrust/thrust/system/cuda/detail/scan.h
Labels: backport branch/2.8.x

#3739 Move `ForceInclusive` parameter of `DispatchScan` before policy
  cub/cub/device/device_scan.cuh
  cub/cub/device/dispatch/dispatch_scan.cuh
  thrust/thrust/system/cuda/detail/async/inclusive_scan.h
  thrust/thrust/system/cuda/detail/scan.h
Labels: cub, breaking

#3742 Fix cub trait deprecations
  cub/cub/util_type.cuh
Labels: backport branch/2.8.x

#3732 Replace raw arm64/x86_64 macros
  libcudacxx/include/cuda/std/__atomic/platform/msvc_to_builtins.h
  libcudacxx/include/cuda/std/__functional/hash.h
  libcudacxx/include/cuda/std/__thread/threading_support.h
  libcudacxx/include/cuda/std/__thread/threading_support_win32.h
Labels: 3.0

#3746 Drop Thrust's cpp_compatibility.h
  docs/repo.toml
  thrust/thrust/detail/config/config.h
  thrust/thrust/detail/config/cpp_compatibility.h
  thrust/thrust/detail/config/memory_resource.h
Labels: thrust, breaking

#3752 Remove unsupported CPU architecture paths (32-bit)
  libcudacxx/include/cuda/std/__functional/hash.h
  libcudacxx/include/cuda/std/__thread/threading_support_win32.h
  libcudacxx/include/cuda/std/limits
  libcudacxx/test/libcudacxx/std/language.support/support.limits/limits/numeric.limits.members/traps.pass.cpp
Labels: 3.0

#3751 fix cuda std namespace
  cub/cub/agent/agent_batch_memcpy.cuh
  cub/cub/agent/agent_histogram.cuh
  cub/cub/agent/agent_merge.cuh
  cub/cub/agent/agent_radix_sort_downsweep.cuh
  cub/cub/agent/agent_radix_sort_histogram.cuh
  cub/cub/agent/agent_radix_sort_onesweep.cuh
  cub/cub/agent/agent_radix_sort_upsweep.cuh
  cub/cub/agent/agent_reduce_by_key.cuh
  cub/cub/agent/agent_rle.cuh
  cub/cub/agent/agent_scan_by_key.cuh
  cub/cub/agent/agent_segmented_radix_sort.cuh
  cub/cub/agent/agent_sub_warp_merge_sort.cuh
  cub/cub/agent/agent_three_way_partition.cuh
  cub/cub/agent/agent_unique_by_key.cuh
  cub/cub/detail/choose_offset.cuh
  cub/cub/detail/fast_modulo_division.cuh
  cub/cub/detail/launcher/cuda_driver.cuh
  cub/cub/detail/temporary_storage.cuh
  cub/cub/device/device_adjacent_difference.cuh
  cub/cub/device/device_for.cuh
  cub/cub/device/device_memcpy.cuh
  cub/cub/device/device_merge.cuh
  cub/cub/device/device_merge_sort.cuh
  cub/cub/device/device_partition.cuh
  cub/cub/device/device_reduce.cuh
  cub/cub/device/device_scan.cuh
  cub/cub/device/device_segmented_reduce.cuh
  cub/cub/device/device_segmented_sort.cuh
  cub/cub/device/dispatch/dispatch_adjacent_difference.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/cub/device/dispatch/dispatch_for_each_in_extents.cuh
  cub/cub/device/dispatch/dispatch_histogram.cuh
  cub/cub/device/dispatch/dispatch_merge.cuh
  cub/cub/device/dispatch/dispatch_merge_sort.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/device/dispatch/dispatch_scan.cuh
  cub/cub/device/dispatch/dispatch_scan_by_key.cuh
  cub/cub/device/dispatch/dispatch_segmented_sort.cuh
  cub/cub/device/dispatch/dispatch_three_way_partition.cuh
  cub/cub/device/dispatch/dispatch_transform.cuh
  cub/cub/device/dispatch/kernels/for_each.cuh
  cub/cub/device/dispatch/tuning/tuning_radix_sort.cuh
  cub/cub/device/dispatch/tuning/tuning_run_length_encode.cuh
Labels: 3.0

#3747 Drop thrust::identity
  docs/thrust/api_docs/function_objects/predefined.rst
  thrust/testing/functional.cu
  thrust/testing/transform_iterator.cu
  thrust/testing/type_traits.cu
  thrust/thrust/functional.h
  thrust/thrust/iterator/detail/transform_iterator.inl
Labels: thrust, breaking

#3743 Drop deprecated entities from CUB util_type
  c2h/include/c2h/bfloat16.cuh
  c2h/include/c2h/half.cuh
  c2h/include/c2h/test_util_vec.h
  cub/cub/block/radix_rank_sort_operations.cuh
  cub/cub/device/dispatch/tuning/tuning_run_length_encode.cuh
  cub/cub/device/dispatch/tuning/tuning_scan.cuh
  cub/cub/device/dispatch/tuning/tuning_select_if.cuh
  cub/cub/device/dispatch/tuning/tuning_unique_by_key.cuh
  cub/cub/util_type.cuh
  cub/cub/warp/specializations/warp_reduce_shfl.cuh
  cub/cub/warp/specializations/warp_scan_shfl.cuh
  cub/cub/warp/warp_scan.cuh
  cub/test/catch2_test_device_reduce.cuh
  cub/test/catch2_test_util_type.cu
  cub/test/test_util.h
Labels: cub, breaking

#3707 [STF] Implement kernel chains in the graph backend without child graphs
  cudax/include/cuda/experimental/__stf/graph/graph_task.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
Labels: stf

#3745 Drop cub::GridBarrier
  cub/cub/cub.cuh
  cub/cub/grid/grid_barrier.cuh
  cub/test/test_grid_barrier.cu
Labels: cub, breaking

#3773 Refactor `cuda/cmath` functions documentation
  docs/libcudacxx/extended_api/math.rst
  docs/libcudacxx/extended_api/math/ceil_div.rst
  docs/libcudacxx/extended_api/math/round_down.rst
  docs/libcudacxx/extended_api/math/round_up.rst
Labels: 3.0

#3756 [STF] Factorize large event lists in CUDA graphs
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/graph/graph_data_interface.cuh
  cudax/include/cuda/experimental/__stf/graph/graph_task.cuh
  cudax/include/cuda/experimental/__stf/graph/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
  cudax/include/cuda/experimental/__stf/utility/memory.cuh
Labels: stf

#3778 [STF] Ensure dot_section::guard is actually movable
  cudax/include/cuda/experimental/__stf/internal/dot.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/dot/section_movable.cu
Labels: stf

#3781 [STF] virtual to_string() method for STF contexts
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_ctx.cuh
Labels: stf

#3782 [STF] Enable freeze on logical tokens
  cudax/include/cuda/experimental/__stf/internal/logical_data.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/freeze/token.cu
Labels: stf

#3740 Move Dispatcher policy hub parameters to the back
  c/parallel/src/reduce.cu
  cub/benchmarks/bench/copy/memcpy.cu
  cub/benchmarks/bench/radix_sort/keys.cu
  cub/benchmarks/bench/radix_sort/pairs.cu
  cub/benchmarks/bench/reduce/base.cuh
  cub/benchmarks/bench/transform_reduce/sum.cu
  cub/cub/device/device_copy.cuh
  cub/cub/device/device_memcpy.cuh
  cub/cub/device/device_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_batch_memcpy.cuh
  cub/cub/device/dispatch/dispatch_radix_sort.cuh
  cub/cub/device/dispatch/dispatch_reduce.cuh
  cub/cub/device/dispatch/dispatch_streaming_reduce.cuh
Labels: cub, breaking

#3811 fix NoopExecutor
  libcudacxx/test/utils/libcudacxx/test/executor.py
Labels: 3.0

#3414 Optimize and clean `countl`, `countr`, `popcount`, `has_single_bit`
  libcudacxx/include/cuda/std/__bit/clz.h
  libcudacxx/include/cuda/std/__bit/countl.h
  libcudacxx/include/cuda/std/__bit/countr.h
  libcudacxx/include/cuda/std/__bit/ctz.h
  libcudacxx/include/cuda/std/__bit/has_single_bit.h
  libcudacxx/include/cuda/std/__bit/integral.h
  libcudacxx/include/cuda/std/__bit/popc.h
  libcudacxx/include/cuda/std/__bit/popcount.h
  libcudacxx/include/cuda/std/__bit/rotate.h
  libcudacxx/include/cuda/std/__cccl/builtin.h
  libcudacxx/include/cuda/std/__type_traits/is_unsigned_integer.h
Labels: 3.0

#3810 fix `-Werror=unused-result`
  libcudacxx/test/libcudacxx/std/iterators/iterator.container/empty.array.fail.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.container/empty.container.fail.cpp
  libcudacxx/test/libcudacxx/std/iterators/iterator.container/empty.initializer_list.fail.cpp
  libcudacxx/test/utils/libcudacxx/test/format.py
Labels: 3.0

#3820 Fix `popc` parentheses warning
  libcudacxx/include/cuda/std/__bit/popc.h
Labels: 3.0

#3748 Drop small deprecated entites
  cub/cub/thread/thread_sort.cuh
  cub/cub/thread/thread_store.cuh
  cub/cub/util_device.cuh
  cub/cub/util_temporary_storage.cuh
  thrust/testing/unittest/testframework.h
  thrust/testing/unittest/util.h
  thrust/thrust/detail/type_deduction.h
  thrust/thrust/limits.h
  thrust/thrust/system/cuda/detail/core/triple_chevron_launch.h
  thrust/thrust/system/cuda/detail/util.h
  thrust/thrust/type_traits/logical_metafunctions.h
Labels: thrust, cub, breaking

#3836 Error when users specialize BaseTraits but not numeric_limits
  cub/cub/util_type.cuh
Labels: cub, breaking

#3765 Refactor `assume_aligned` implementation
  libcudacxx/include/cuda/std/__memory/assume_aligned.h
  libcudacxx/test/libcudacxx/std/utilities/memory/ptr.align/assume_aligned.pass.cpp
  libcudacxx/test/libcudacxx/std/utilities/memory/ptr.align/assume_aligned.runfail.cpp
  libcudacxx/test/utils/libcudacxx/test/executor.py
Labels: 3.0

#3883 Document `cuda::maximum`, `cuda::minimum`
  docs/libcudacxx/extended_api/functional.rst
  docs/libcudacxx/extended_api/functional/maximum_minimum.rst
Labels: 3.0

#3894 Update Blackwell PTX instruction availability tables
  docs/libcudacxx/ptx/instructions.rst
Labels: backport branch/2.8.x

#3241 PTX `shfl_sync`
  docs/libcudacxx/ptx/instructions.rst
  docs/libcudacxx/ptx/instructions/generated/shfl_sync.rst
  docs/libcudacxx/ptx/instructions/shfl_sync.rst
  libcudacxx/include/cuda/__ptx/instructions/shfl_sync.h
  libcudacxx/include/cuda/ptx
  libcudacxx/test/libcudacxx/cuda/ptx/ptx.shfl.compile.pass.cpp
Labels: blocked, 3.0

#3905 Drop deprecated iterators from Thrust cuda utils
  thrust/thrust/system/cuda/detail/util.h
Labels: thrust, breaking

#3868 [STF] Executable CUDA graphs caching policies
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/async_resources_handle.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/executable_graph_cache.cuh
  cudax/include/cuda/experimental/__stf/utility/source_location.cuh
  cudax/include/cuda/experimental/stf.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/graph/get_cache_stats.cu
  cudax/test/stf/graph/graph_cache_policy.cu
  cudax/test/stf/utility/source_location_map.cu
Labels: stf

#3863 Minimize usage of cub::Traits
  c2h/include/c2h/bfloat16.cuh
  c2h/include/c2h/half.cuh
  c2h/include/c2h/test_util_vec.h
  cub/benchmarks/bench/reduce/arg_extrema.cu
  cub/cub/device/device_reduce.cuh
  cub/cub/device/device_segmented_reduce.cuh
  cub/cub/util_type.cuh
  cub/examples/device/example_device_radix_sort_custom.cu
  cub/test/catch2_test_device_reduce.cuh
  cub/test/catch2_test_device_segmented_sort_keys.cu
  cub/test/catch2_test_util_type.cu
  cub/test/test_util.h
Labels: cub, breaking

#3934 Drop public access to RegBoundScaling/MemBoundScaling
  cub/cub/util_arch.cuh
Labels: cub, breaking

#3935 Drop deprecated features from CUB util_ptx.cuh
  cub/cub/util_ptx.cuh
Labels: cub, breaking

#3925 [STF] Thread safe graph_ctx
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/graph/graph_task.cuh
  cudax/include/cuda/experimental/__stf/internal/acquire_release.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/parallel_for_scope.cuh
  cudax/test/stf/CMakeLists.txt
  cudax/test/stf/threads/axpy-threads-graph-capture.cu
  cudax/test/stf/threads/axpy-threads-graph.cu
Labels: stf

#3296 Optimize `bit_floor`, `bit_ceil`, `bit_width`
  libcudacxx/include/cuda/std/__bit/integral.h
Labels: 3.0

#3944 [STF] Remove unmaintained CUDASTF_DEBUG option
  CMakePresets.json
  cudax/CMakeLists.txt
  cudax/cmake/cudaxSTFConfigureTarget.cmake
  cudax/include/cuda/experimental/__stf/graph/graph_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_ctx.cuh
  cudax/include/cuda/experimental/__stf/internal/executable_graph_cache.cuh
  cudax/include/cuda/experimental/__stf/stream/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_ctx.cuh
  cudax/include/cuda/experimental/__stf/stream/stream_task.cuh
Labels: stf

#3959 Improve `<cuda/std/bit>` documentation
  docs/libcudacxx/standard_api/numerics_library/bit.rst
Labels: 3.0
