Repository NVIDIA/cccl, pull requests merged in 2025-06, with the labels that each got.

#4889 Generate a version from git/JSON for packages
  ci/build_cuda_parallel_wheel.sh
  ci/generate_version.sh
  python/cuda_parallel/pyproject.toml
Labels: infrastructure

#4840 Improve `device_accessor` memory space check
  libcudacxx/include/cuda/__mdspan/host_device_accessor.h
  libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/device_accessor/device_accessor.runfail.cpp
  libcudacxx/test/libcudacxx/cuda/containers/views/mdspan/host_accessor/host_device_accessor.pass.cpp
Labels: 3.1.0, CI 100%

#4963 Fix `cuda::warp_match_all` test case
  libcudacxx/test/libcudacxx/cuda/warp/warp_match.pass.cpp
Labels: 3.1.0

#5006 [CUDAX] Add sm_103 traits
  cudax/include/cuda/experimental/__device/arch_traits.cuh
  cudax/test/device/arch_traits.cu
Labels: backport branch/3.0.x

#5010 Avoid deprecated `cudaGetDriverEntryPoint`
  libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_tensor.pass.cpp
  libcudacxx/test/libcudacxx/cuda/barrier/cp_async_bulk_tensor_generic.h
Labels: backport branch/3.0.x

#4842 Split Optimize `WarpReduce` PR - Part3 `c2h`
  c2h/CMakeLists.txt
  c2h/generators.cu
  c2h/generators_vector.cu
  c2h/include/c2h/bfloat16.cuh
  c2h/include/c2h/catch2_test_helper.h
  c2h/include/c2h/check_results.cuh
  c2h/include/c2h/checked_allocator.cuh
  c2h/include/c2h/device_policy.h
  c2h/include/c2h/extended_types.h
  c2h/include/c2h/generators.cuh
  c2h/include/c2h/generators.h
  c2h/include/c2h/half.cuh
  c2h/include/c2h/operator.cuh
  c2h/include/c2h/test_util_vec.h
  c2h/include/c2h/vector.h
  cub/test/catch2_test_printing.cu
  cub/test/internal/catch2_test_fast_div_mod.cu
  cub/test/test_allocator.cu
  cub/test/test_device_batch_copy.cu
  cub/test/test_util.h
  cub/test/warp/catch2_test_warp_reduce.cu
Labels: 3.1.0

#4949 Extend nightly SM build coverage
  ci/matrix.yaml
  cub/cub/device/dispatch/dispatch_transform.cuh
  cub/test/catch2_test_util_device.cu
  libcudacxx/include/cuda/__functional/for_each_canceled.h
  libcudacxx/include/nv/detail/__target_macros
  libcudacxx/include/nv/target
  libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr.createpolicy.pass.cpp
Labels: backport branch/3.0.x

#5036 Handle upcoming vector type change
  c2h/generators_vector.cu
  c2h/include/c2h/catch2_test_helper.h
  c2h/include/c2h/fill_striped.h
  c2h/include/c2h/test_util_vec.h
  cub/cub/thread/thread_load.cuh
  cub/cub/thread/thread_store.cuh
  cub/cub/util_type.cuh
  cub/test/catch2_test_block_reduce.cu
  cub/test/catch2_test_block_scan.cu
  cub/test/catch2_test_device_adjacent_difference_substract_right.cu
  cub/test/catch2_test_device_partition_flagged.cu
  cub/test/catch2_test_device_partition_if.cu
  cub/test/catch2_test_device_reduce.cu
  cub/test/catch2_test_device_reduce.cuh
  cub/test/catch2_test_device_reduce_by_key.cu
  cub/test/catch2_test_device_scan.cu
  cub/test/catch2_test_device_scan_by_key.cu
  cub/test/catch2_test_device_scan_by_key_iterators.cu
  cub/test/catch2_test_device_segmented_reduce.cu
  cub/test/catch2_test_device_select_flagged.cu
  cub/test/catch2_test_device_select_flagged_if.cu
  cub/test/catch2_test_device_select_if.cu
  cub/test/catch2_test_device_select_unique.cu
  cub/test/catch2_test_device_select_unique_by_key.cu
  cub/test/catch2_test_iterator.cu
  cub/test/catch2_test_warp_exchange_smem.cu
  cub/test/catch2_test_warp_scan.cu
  cub/test/test_util.h
  cub/test/warp/catch2_test_warp_reduce.cu
  cub/test/warp/catch2_test_warp_segmented_reduce.cu
  libcudacxx/include/cuda/std/__tuple_dir/vector_types.h
  thrust/thrust/type_traits/is_trivially_relocatable.h
Labels: backport branch/3.0.x

#5045 `thrust::cuda::pinned_memory_resource` should dispatch to the host system
  thrust/testing/universal_memory.cu
  thrust/thrust/system/cpp/pointer.h
  thrust/thrust/system/cuda/memory_resource.h
  thrust/thrust/system/cuda/pointer.h
  thrust/thrust/system/omp/pointer.h
  thrust/thrust/system/tbb/pointer.h
  thrust/thrust/universal_allocator.h
Labels: backport branch/3.0.x
