Repository NVIDIA/cccl, pull requests merged in 2025-05, with the labels that each got.

#4595 Exclude gcc-11, gcc-10 from `annotated_ptr` constexpr test
  libcudacxx/test/libcudacxx/cuda/annotated_ptr/access_property_constexpr.pass.cpp
  libcudacxx/test/libcudacxx/cuda/annotated_ptr/annotated_ptr_constexpr.pass.cpp
Labels: 3.1.0

#4613 Update license of CTK files in libcu++
  libcudacxx/include/cuda/__annotated_ptr/access_property.h
  libcudacxx/include/cuda/__annotated_ptr/access_property_encoding.h
  libcudacxx/include/cuda/__annotated_ptr/annotated_ptr.h
  libcudacxx/include/cuda/__annotated_ptr/annotated_ptr_base.h
  libcudacxx/include/cuda/__annotated_ptr/apply_access_property.h
  libcudacxx/include/cuda/__annotated_ptr/associate_access_property.h
  libcudacxx/include/cuda/access_property
  libcudacxx/include/cuda/annotated_ptr
  libcudacxx/include/cuda/pipeline
Labels: 3.1.0

#4586 Always bypass automatic atomic storage checks to prevent potential compiler issues
  libcudacxx/include/cuda/std/detail/libcxx/include/__config
  libcudacxx/test/libcudacxx/cuda/atomics/atomic.local.pass.cpp
Labels: 2.8.0, backport branch/2.8.x

#4703 [STF] Improvements for the cached fifo allocator and misc improvements
  cudax/include/cuda/experimental/__stf/allocators/adapters.cuh
  cudax/include/cuda/experimental/__stf/allocators/cached_allocator.cuh
  cudax/include/cuda/experimental/__stf/internal/backend_allocator_setup.cuh
  cudax/include/cuda/experimental/__stf/internal/executable_graph_cache.cuh
  cudax/include/cuda/experimental/__stf/internal/task_dep.cuh
  cudax/include/cuda/experimental/__stf/places/places.cuh
Labels: stf

#4679 Build and test python wheels in CI
  .devcontainer/cccl-entrypoint.sh
  .devcontainer/cuda12.0-gcc10/devcontainer.json
  .devcontainer/cuda12.0-gcc11/devcontainer.json
  .devcontainer/cuda12.0-gcc12/devcontainer.json
  .devcontainer/cuda12.0-gcc7/devcontainer.json
  .devcontainer/cuda12.0-gcc8/devcontainer.json
  .devcontainer/cuda12.0-gcc9/devcontainer.json
  .devcontainer/cuda12.0-llvm14/devcontainer.json
  .devcontainer/cuda12.8-gcc10/devcontainer.json
  .devcontainer/cuda12.8-gcc11/devcontainer.json
  .devcontainer/cuda12.8-gcc12/devcontainer.json
  .devcontainer/cuda12.8-gcc13/devcontainer.json
  .devcontainer/cuda12.8-gcc7/devcontainer.json
  .devcontainer/cuda12.8-gcc8/devcontainer.json
  .devcontainer/cuda12.8-gcc9/devcontainer.json
  .devcontainer/cuda12.8-llvm14/devcontainer.json
  .devcontainer/cuda12.8-llvm15/devcontainer.json
  .devcontainer/cuda12.8-llvm16/devcontainer.json
  .devcontainer/cuda12.8-llvm17/devcontainer.json
  .devcontainer/cuda12.8-llvm18/devcontainer.json
  .devcontainer/cuda12.8-llvm19/devcontainer.json
  .devcontainer/cuda12.8-nvhpc25.3/devcontainer.json
  .devcontainer/cuda12.8ext-gcc13/devcontainer.json
  .devcontainer/devcontainer.json
  .devcontainer/launch.sh
  .github/actions/workflow-build/build-workflow.py
  .github/actions/workflow-run-job-linux/action.yml
  .github/workflows/workflow-dispatch-two-stage-linux.yml
  ci/build_cuda_cccl_python.sh
  ci/build_cuda_cooperative_python.sh
  ci/build_cuda_parallel_python.sh
  ci/matrix.yaml
  ci/pyenv_helper.sh
  ci/test_cuda_cccl_python.sh
  ci/test_cuda_cooperative_python.sh
  ci/test_cuda_parallel_python.sh
  python/cuda_parallel/pyproject.toml
Labels: 3.0

#4705 [STF] Ensure we generate CUDA graphs which always have the same topology
  cudax/include/cuda/experimental/__stf/graph/internal/event_types.cuh
  cudax/include/cuda/experimental/__stf/internal/async_prereq.cuh
Labels: stf

#4729 Introduce temp storage alignment awareness to cuda.cooperative.
  python/cuda_cooperative/cuda/cooperative/experimental/_common.py
  python/cuda_cooperative/cuda/cooperative/experimental/_types.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_load_store.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_merge_sort.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_radix_sort.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_reduce.py
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_scan.py
  python/cuda_cooperative/cuda/cooperative/experimental/warp/_warp_merge_sort.py
  python/cuda_cooperative/cuda/cooperative/experimental/warp/_warp_reduce.py
  python/cuda_cooperative/cuda/cooperative/experimental/warp/_warp_scan.py
  python/cuda_cooperative/tests/test_block_reduce.py
  python/cuda_cooperative/tests/test_block_scan.py
Labels: 3.0

#4739 Avoid deprecated CUDART usage. (#4505)
  cub/test/CMakeLists.txt
  cub/test/test_util.h
  cudax/include/cuda/experimental/__device/attributes.cuh
  cudax/test/device/device_smoke.cu
Labels: 3.0

#4715 Split Optimize Warp Reduce PR - libcu++ part
  libcudacxx/include/cuda/std/__internal/namespaces.h
Labels: 3.1.0, CI Passed

#4756 Fix cuda.coop limitation preventing user-defined types when items_per_thread > 1 in block scan module.
  python/cuda_cooperative/cuda/cooperative/experimental/block/_block_scan.py
  python/cuda_cooperative/tests/helpers.py
  python/cuda_cooperative/tests/test_block_scan.py
  python/cuda_cooperative/tests/test_block_scan_api.py
Labels: 3.0

#2669 Enable Catch2 tests in Thrust
  thrust/testing/CMakeLists.txt
  thrust/testing/adjacent_difference.cu
  thrust/testing/alignment.cu
  thrust/testing/binary_search.cu
  thrust/testing/catch2_test_adjacent_difference.cu
  thrust/testing/catch2_test_alignment.cu
  thrust/testing/catch2_test_binary_search.cu
  thrust/testing/catch2_test_helper.h
  thrust/testing/unittest/testframework.cu
  thrust/testing/unittest/testframework.h
Labels: thrust

#4854 Fix `lane_mask` documentation
  docs/libcudacxx/extended_api/warp.rst
  docs/libcudacxx/extended_api/warp/lane_mask.rst
Labels: 3.1.0, CI 100%

#4851 Ensuring CTK minor version compatibility for cccl.c.parallel
  c/parallel/src/nvrtc/command_list.h
  c/parallel/src/nvrtc/nvjitlink_helper.h
  c/parallel/src/util/context.h
  c/parallel/src/util/errors.h
Labels: cuda.parallel, CCCL-C
